version: "3"
services:
  server:
    image: node:12.18.4
    ports:
      - 3000:3000
    environment:
      - PGUSER=brogrammers
      - PGHOST=db
      - PGPASSWORD=stridePass
      - PGDATABASE=stride
    #   - DATABASE_URL=postgres://zakgogi:scorepass97@db:5432/scores
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./API
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=stride
      - POSTGRES_USER=brogrammers
      - POSTGRES_PASSWORD=stridePass
volumes:
  dbdata:
