version: "3"
services:
  server:
    container_name: test_api
    image: node:12.18.4
    ports:
      - 5000:5000
    environment:
      - PGUSER=brogrammers
      - PGHOST=db
      - PGPASSWORD=stridePass
      - PGDATABASE=stride
    #   - DATABASE_URL=postgres://zakgogi:scorepass97@db:5432/scores
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./API
        target: /code
    working_dir: /code
    tty: true
    # command: bash -c "npm install && npm test"
  db:
    image: postgres:latest
    volumes:
      - "test_data:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=stride
      - POSTGRES_USER=brogrammers
      - POSTGRES_PASSWORD=stridePass
volumes:
  test_data:
